import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>ESIA App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <div className="container">
          <h2 className="mt-4 text-center text-base font-bold">
            Escuela Superior de Ingeniería y Arquitectura
          </h2>
          <h2 className="text-center text-lg font-bold">Unidad Tecamachalco</h2>

          {/* eslint-disable-next-line @next/next/no-img-element*/}
          <img
            className="m-auto mt-4 aspect-[89/140] w-12"
            src={"/assets/imgs/esia.png"}
            alt=""
          />

          <div className="mt-24 flex flex-col items-center justify-center">
            <button className="block w-48 rounded-full bg-gradient-to-r from-azul to-azul-claro py-[10px] text-sm text-blanco">
              ALUMNOS
            </button>
            <button className="block w-48 rounded-full bg-gradient-to-r from-azul to-azul-claro py-[10px] text-sm text-blanco mt-3">
              DOCENTES
            </button>
            <button className="block w-48 rounded-full bg-gradient-to-r from-azul to-azul-claro py-[10px] text-sm text-blanco mt-3">
              POSGRADO
            </button>
          </div>
        </div>
      </main>
    </>
  );
}
