import Head from "next/head";
import React, { type PropsWithChildren } from "react";

export const LayoutPage = ({ children }: PropsWithChildren) => {
  return (
    <>
      <Head>
        <title>ESIA App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>{children}</main>
    </>
  );
};
